steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/flask-app:$SHORT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'  # Explicit push (optional but good practice)
    args: ['push', 'gcr.io/$PROJECT_ID/flask-app:$SHORT_SHA']

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'gcloud'
    args: [
      'run',
      'deploy',
      'flask-app',  # Replace with your service name
      '--image',
      'gcr.io/$PROJECT_ID/flask-app:$SHORT_SHA',
      '--region',
      'global',  # Replace with your region
      '--platform',
      'managed',
      '--allow-unauthenticated' # Only for testing. In production, use authentication.
    ]

images: ['gcr.io/$PROJECT_ID/flask-app:$SHORT_SHA']

serviceAccount: 'projects/project-test-445208/serviceAccounts/abstractcategorizationweb@project-test-445208.iam.gserviceaccount.com'

timeout: '1800s'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_MEDIUM'
  diskSizeGb: 5